 
 
# Template script intended to jumpstart the user to run Modus Automatic Test Pattern Generation (ATPG) software.
 
#  Generated by Genus(TM) Synthesis Solution 18.10-p003_1
 
# Modus ATPG Script
 
#-------------------------------------------------------------------------------
# INITIALIZE VARIABLES
#-------------------------------------------------------------------------------
# "set_db workdir" is recommended to be set first to initialize where the Database is to be located
# WORKDIR Tcl variable can be used in the script to reference file locations
set WORKDIR 		$::env(ATPG_DIR)/syn
set DESIGN 			riscv_core
set_db workdir 	$WORKDIR;                                  # Specify the directory for the ATPG database
 
# Configure the database
set_option stdout     summary;                                # Only print a summary for each command to the terminal
                                                          # Logs contain the complete command output
set ::env(CDS_LIC_REPORT) yes
# test_checks.tcl provides check_log proc to stop script on message severity
source  $::env(Install_Dir)/bin/64bit/test_checks.tcl;    # Load test_checks.tcl from Modus installation - provides check_log below
set STOP_ON_MSG_SEV ERROR;                                # Messagee severity for check_log to stop at (ERROR, WARNING_SEVERE, WARNING)
set LOGDIR         $WORKDIR/testresults/logs;            # Location of logs for check_log
 
file delete -force $WORKDIR/tbdata;                       # Delete Test Database
file delete -force $WORKDIR/testresults;                  # Delete Test Output Files/Logs
 
 
 
#-------------------------------------------------------------------------------
# BUILD THE LOGIC MODEL
#-------------------------------------------------------------------------------
build_model \
    -cell	 								${DESIGN} \
    -techlib	 						$::env(FE_VER_LIB)/*.v \
    -designsource					$::env(SYN_DFT_NET_DIR)/${DESIGN}.syn.v \
		-blackboxoutputs			z  \
    -allowmissingmodules	no \

check_log log_build_model
 
#-------------------------------------------------------------------------------
# BUILD THE TEST MODEL
#-------------------------------------------------------------------------------
build_testmode \
    -testmode	 	FULLSCAN \
		-assignfile $::env(ATPG_DIR)/syn/${DESIGN}.FULLSCAN.pinassign \
    -modedef	 	FULLSCAN \
		-delaymode	zero \
 
check_log log_build_testmode_FULLSCAN
 
#-------------------------------------------------------------------------------
# VERIFY THE TEST MODEL
#-------------------------------------------------------------------------------
verify_test_structures \
    -testmode       FULLSCAN \
    -xclockanalysis yes \
    -testxsource    yes \ 

check_log log_verify_test_structures_FULLSCAN

#-------------------------------------------------------------------------------
# REPORT THE TEST MODEL
#-------------------------------------------------------------------------------
report_test_structures \
    -testmode	 				FULLSCAN \
		-reportscanchain 	all \
 
check_log log_report_test_structures_FULLSCAN
 
#-------------------------------------------------------------------------------
# BUILD THE FAULT MODEL
#-------------------------------------------------------------------------------
build_faultmodel \
    -includedynamic	 yes \
 
check_log log_build_faultmodel
 
report_faults \
    -faulttype all \
    -reportkey yes
report_fault_statistics

analyze_testability \
    -testmode    FULLSCAN \

#-------------------------------------------------------------------------------
# ATPG - TEST GENERATION
#-------------------------------------------------------------------------------
create_logic_tests \
    -testmode   FULLSCAN \
    -experiment ${DESIGN}_atpg \

create_sequential_tests \
    -testmode   FULLSCAN \
    -experiment ${DESIGN}_atpg \
    -append     yes \

create_logic_delay_tests \
    -testmode   FULLSCAN \
    -experiment ${DESIGN}_atpg \
    -append     yes \

create_iddq_tests \
    -testmode   FULLSCAN \
    -experiment ${DESIGN}_atpg \
    -append     yes \

report_fault_statistics \
    -experiment ${DESIGN}_atpg \
    -testmode   FULLSCAN \

report_faults \
    -testmode   FULLSCAN \
    -experiment ${DESIGN}_atpg \
    -faulttype  all \
    -reportkey  yes \

check_log log_create_logic_tests_FULLSCAN_riscv_core_atpg

#-------------------------------------------------------------------------------
# ATPG - Report the Scan and Capture Switching
#-------------------------------------------------------------------------------
write_toggle_gram \
    -experiment ${DESIGN}_atpg \
    -testmode   FULLSCAN \

#-------------------------------------------------------------------------------
# ATPG - Save Experiment to the Master Database for the Testmode
#-------------------------------------------------------------------------------
commit_tests \
    -testmode     FULLSCAN \
    -inexperiment ${DESIGN}_atpg \

check_log log_commit_tests_FULLSCAN_riscv_core_atpg

#-------------------------------------------------------------------------------
# VERILOG VECTORS - For PARALLEL Simulation
#-------------------------------------------------------------------------------
write_vectors \
    -testmode   FULLSCAN \
    -language   verilog \
    -scanformat parallel \
    -exportdir  $WORKDIR/testresults/verilog/FULLSCAN_PARALLEL \
    -logfile    $WORKDIR/testresults/logs/log_write_vectors_FULLSCAN_${DESIGN}_atpg

check_log log_write_vectors_FULLSCAN_riscv_core_atpg


exit
