#!/bin/ksh
 
# Template script for running Cadence Incisive simulator (NCSIM) on Cadence Encounter Test generated test vectors.
 
#  Generated by Genus(TM) Synthesis Solution 18.10-p003_1
 
export WORKDIR=/users/Cours/ele8304/12/Labs/lab2/implementation/atpg/syn
export WORKDIR=${ATPG_DIR}/syn
export DESIGN=riscv_core
 
xrun \
   +access+rwc \
   +xmstatus \
   +xm64bit \
   +TESTFILE1=$WORKDIR/testresults/verilog/FULLSCAN_PARALLEL/VER.FULLSCAN.data.scan.ex1.ts1.verilog \
   +TESTFILE2=$WORKDIR/testresults/verilog/FULLSCAN_PARALLEL/VER.FULLSCAN.data.logic.ex1.ts2.verilog \
   +TESTFILE2=$WORKDIR/testresults/verilog/FULLSCAN_PARALLEL/VER.FULLSCAN.data.logic.ex1.ts3.verilog \
   +TESTFILE2=$WORKDIR/testresults/verilog/FULLSCAN_PARALLEL/VER.FULLSCAN.data.IDDq.ex1.ts4.verilog \
   +HEARTBEAT \
   +FAILSET \
   +xmtimescale+1ns/1ps \
   +xmoverride_timescale \
   +xmseq_udp_delay+2ps \
   +libext+.v+.V+.z+.Z+.gz \
   +xmlibdirname+$WORKDIR/Inca_libs_12_06_09 \
   -l $WORKDIR/ncverilog_FULLSCAN.log \
	 -v /CMC/kits/GPDK45/gsclib045/gsclib045/verilog/fast_vdd1v0_basicCells.v \
	    ${SYN_DFT_NET_DIR}/${DESIGN}.syn.v \
			$WORKDIR/testresults/verilog/FULLSCAN_PARALLEL/VER.FULLSCAN.mainsim.v

