
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Dec  9 2021 01:38:07 EST (Dec  9 2021 06:38:07 UTC)

// Verification Directory fv/riscv_pc 

module riscv_pc(i_clk, i_rstn, i_stall, i_transfert, i_target, o_pc);
  input i_clk, i_rstn, i_stall, i_transfert;
  input [31:0] i_target;
  output [31:0] o_pc;
  wire i_clk, i_rstn, i_stall, i_transfert;
  wire [31:0] i_target;
  wire [31:0] o_pc;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122;
  DFFRHQX8 \s_pc_reg[31] (.RN (i_rstn), .CK (i_clk), .D (n_122), .Q
       (o_pc[31]));
  OAI2BB1X1 g2379__8780(.A0N (i_target[31]), .A1N (n_116), .B0 (n_121),
       .Y (n_122));
  DFFRHQX8 \s_pc_reg[30] (.RN (i_rstn), .CK (i_clk), .D (n_120), .Q
       (o_pc[30]));
  AOI22X1 g2381__4296(.A0 (n_114), .A1 (n_118), .B0 (o_pc[31]), .B1
       (n_119), .Y (n_121));
  DFFRHQX8 \s_pc_reg[29] (.RN (i_rstn), .CK (i_clk), .D (n_117), .Q
       (o_pc[29]));
  OAI2BB1X1 g2383__3772(.A0N (o_pc[30]), .A1N (n_119), .B0 (n_115), .Y
       (n_120));
  MXI2XL g2386__1474(.A (n_111), .B (o_pc[30]), .S0 (o_pc[31]), .Y
       (n_118));
  OAI2BB1X1 g2384__4547(.A0N (i_target[29]), .A1N (n_116), .B0 (n_113),
       .Y (n_117));
  AOI32X1 g2385__9682(.A0 (n_114), .A1 (n_1), .A2 (n_112), .B0
       (i_target[30]), .B1 (n_116), .Y (n_115));
  DFFRHQX8 \s_pc_reg[28] (.RN (i_rstn), .CK (i_clk), .D (n_110), .Q
       (o_pc[28]));
  AOI22X1 g2388__2683(.A0 (n_114), .A1 (n_109), .B0 (i_stall), .B1
       (o_pc[29]), .Y (n_113));
  OAI21X1 g2387__1309(.A0 (n_5), .A1 (n_112), .B0 (n_6), .Y (n_119));
  NAND2X1 g2390__6877(.A (o_pc[30]), .B (n_112), .Y (n_111));
  OAI2BB1X1 g2392__2900(.A0N (i_target[28]), .A1N (n_116), .B0 (n_108),
       .Y (n_110));
  ADDHX1 g2391__2391(.A (o_pc[29]), .B (n_105), .CO (n_112), .S
       (n_109));
  AOI22X1 g2393__7675(.A0 (n_114), .A1 (n_106), .B0 (i_stall), .B1
       (o_pc[28]), .Y (n_108));
  DFFRHQX8 \s_pc_reg[27] (.RN (i_rstn), .CK (i_clk), .D (n_107), .Q
       (o_pc[27]));
  OAI2BB1X1 g2396__7118(.A0N (i_target[27]), .A1N (n_116), .B0 (n_104),
       .Y (n_107));
  ADDHX1 g2395__8757(.A (o_pc[28]), .B (n_101), .CO (n_105), .S
       (n_106));
  DFFRHQX8 \s_pc_reg[26] (.RN (i_rstn), .CK (i_clk), .D (n_103), .Q
       (o_pc[26]));
  AOI22X1 g2397__1786(.A0 (n_114), .A1 (n_102), .B0 (i_stall), .B1
       (o_pc[27]), .Y (n_104));
  OAI2BB1X1 g2400__5953(.A0N (i_target[26]), .A1N (n_116), .B0 (n_100),
       .Y (n_103));
  ADDHX1 g2399__5703(.A (o_pc[27]), .B (n_97), .CO (n_101), .S (n_102));
  DFFRHQX8 \s_pc_reg[25] (.RN (i_rstn), .CK (i_clk), .D (n_99), .Q
       (o_pc[25]));
  AOI22X1 g2401__7114(.A0 (n_114), .A1 (n_98), .B0 (i_stall), .B1
       (o_pc[26]), .Y (n_100));
  OAI2BB1X1 g2404__5266(.A0N (i_target[25]), .A1N (n_116), .B0 (n_96),
       .Y (n_99));
  ADDHX1 g2403__2250(.A (o_pc[26]), .B (n_93), .CO (n_97), .S (n_98));
  AOI22X1 g2405__6083(.A0 (n_114), .A1 (n_94), .B0 (i_stall), .B1
       (o_pc[25]), .Y (n_96));
  DFFRHQX8 \s_pc_reg[24] (.RN (i_rstn), .CK (i_clk), .D (n_95), .Q
       (o_pc[24]));
  OAI2BB1X1 g2408__2703(.A0N (i_target[24]), .A1N (n_116), .B0 (n_92),
       .Y (n_95));
  ADDHX1 g2407__5795(.A (o_pc[25]), .B (n_89), .CO (n_93), .S (n_94));
  AOI22X1 g2409__7344(.A0 (n_114), .A1 (n_90), .B0 (i_stall), .B1
       (o_pc[24]), .Y (n_92));
  DFFRHQX8 \s_pc_reg[23] (.RN (i_rstn), .CK (i_clk), .D (n_91), .Q
       (o_pc[23]));
  OAI2BB1X1 g2412__1840(.A0N (i_target[23]), .A1N (n_116), .B0 (n_88),
       .Y (n_91));
  ADDHX1 g2411__5019(.A (o_pc[24]), .B (n_85), .CO (n_89), .S (n_90));
  AOI22X1 g2413__1857(.A0 (n_114), .A1 (n_86), .B0 (i_stall), .B1
       (o_pc[23]), .Y (n_88));
  DFFRHQX8 \s_pc_reg[22] (.RN (i_rstn), .CK (i_clk), .D (n_87), .Q
       (o_pc[22]));
  OAI2BB1X1 g2416__9906(.A0N (i_target[22]), .A1N (n_116), .B0 (n_84),
       .Y (n_87));
  ADDHX1 g2415__8780(.A (o_pc[23]), .B (n_81), .CO (n_85), .S (n_86));
  DFFRHQX8 \s_pc_reg[21] (.RN (i_rstn), .CK (i_clk), .D (n_83), .Q
       (o_pc[21]));
  AOI22X1 g2417__4296(.A0 (n_114), .A1 (n_82), .B0 (i_stall), .B1
       (o_pc[22]), .Y (n_84));
  OAI2BB1X1 g2420__3772(.A0N (i_target[21]), .A1N (n_116), .B0 (n_80),
       .Y (n_83));
  ADDHX1 g2419__1474(.A (o_pc[22]), .B (n_77), .CO (n_81), .S (n_82));
  DFFRHQX8 \s_pc_reg[20] (.RN (i_rstn), .CK (i_clk), .D (n_79), .Q
       (o_pc[20]));
  AOI22X1 g2421__4547(.A0 (n_114), .A1 (n_78), .B0 (i_stall), .B1
       (o_pc[21]), .Y (n_80));
  OAI2BB1X1 g2424__9682(.A0N (i_target[20]), .A1N (n_116), .B0 (n_76),
       .Y (n_79));
  ADDHX1 g2423__2683(.A (o_pc[21]), .B (n_73), .CO (n_77), .S (n_78));
  DFFRHQX8 \s_pc_reg[19] (.RN (i_rstn), .CK (i_clk), .D (n_75), .Q
       (o_pc[19]));
  AOI22X1 g2425__1309(.A0 (n_114), .A1 (n_74), .B0 (i_stall), .B1
       (o_pc[20]), .Y (n_76));
  OAI2BB1X1 g2428__6877(.A0N (i_target[19]), .A1N (n_116), .B0 (n_72),
       .Y (n_75));
  ADDHX1 g2427__2900(.A (o_pc[20]), .B (n_69), .CO (n_73), .S (n_74));
  DFFRHQX8 \s_pc_reg[18] (.RN (i_rstn), .CK (i_clk), .D (n_71), .Q
       (o_pc[18]));
  AOI22X1 g2429__2391(.A0 (n_114), .A1 (n_70), .B0 (i_stall), .B1
       (o_pc[19]), .Y (n_72));
  OAI2BB1X1 g2432__7675(.A0N (i_target[18]), .A1N (n_116), .B0 (n_68),
       .Y (n_71));
  ADDHX1 g2431__7118(.A (o_pc[19]), .B (n_65), .CO (n_69), .S (n_70));
  AOI22X1 g2433__8757(.A0 (n_114), .A1 (n_66), .B0 (i_stall), .B1
       (o_pc[18]), .Y (n_68));
  DFFRHQX8 \s_pc_reg[17] (.RN (i_rstn), .CK (i_clk), .D (n_67), .Q
       (o_pc[17]));
  OAI2BB1X1 g2436__1786(.A0N (i_target[17]), .A1N (n_116), .B0 (n_64),
       .Y (n_67));
  ADDHX1 g2435__5953(.A (o_pc[18]), .B (n_61), .CO (n_65), .S (n_66));
  AOI22X1 g2437__5703(.A0 (n_114), .A1 (n_62), .B0 (i_stall), .B1
       (o_pc[17]), .Y (n_64));
  DFFRHQX8 \s_pc_reg[16] (.RN (i_rstn), .CK (i_clk), .D (n_63), .Q
       (o_pc[16]));
  OAI2BB1X1 g2440__7114(.A0N (i_target[16]), .A1N (n_116), .B0 (n_60),
       .Y (n_63));
  ADDHX1 g2439__5266(.A (o_pc[17]), .B (n_57), .CO (n_61), .S (n_62));
  AOI22X1 g2441__2250(.A0 (n_114), .A1 (n_58), .B0 (i_stall), .B1
       (o_pc[16]), .Y (n_60));
  DFFRHQX8 \s_pc_reg[15] (.RN (i_rstn), .CK (i_clk), .D (n_59), .Q
       (o_pc[15]));
  OAI2BB1X1 g2444__6083(.A0N (i_target[15]), .A1N (n_116), .B0 (n_56),
       .Y (n_59));
  ADDHX1 g2443__2703(.A (o_pc[16]), .B (n_53), .CO (n_57), .S (n_58));
  AOI22X1 g2445__5795(.A0 (n_114), .A1 (n_54), .B0 (i_stall), .B1
       (o_pc[15]), .Y (n_56));
  DFFRHQX8 \s_pc_reg[14] (.RN (i_rstn), .CK (i_clk), .D (n_55), .Q
       (o_pc[14]));
  OAI2BB1X1 g2448__7344(.A0N (i_target[14]), .A1N (n_116), .B0 (n_52),
       .Y (n_55));
  ADDHX1 g2447__1840(.A (o_pc[15]), .B (n_49), .CO (n_53), .S (n_54));
  AOI22X1 g2449__5019(.A0 (n_114), .A1 (n_50), .B0 (i_stall), .B1
       (o_pc[14]), .Y (n_52));
  DFFRHQX8 \s_pc_reg[13] (.RN (i_rstn), .CK (i_clk), .D (n_51), .Q
       (o_pc[13]));
  OAI2BB1X1 g2452__1857(.A0N (i_target[13]), .A1N (n_116), .B0 (n_48),
       .Y (n_51));
  ADDHX1 g2451__9906(.A (o_pc[14]), .B (n_45), .CO (n_49), .S (n_50));
  DFFRHQX8 \s_pc_reg[12] (.RN (i_rstn), .CK (i_clk), .D (n_47), .Q
       (o_pc[12]));
  AOI22X1 g2453__8780(.A0 (n_114), .A1 (n_46), .B0 (i_stall), .B1
       (o_pc[13]), .Y (n_48));
  OAI2BB1X1 g2456__4296(.A0N (i_target[12]), .A1N (n_116), .B0 (n_44),
       .Y (n_47));
  ADDHX1 g2455__3772(.A (o_pc[13]), .B (n_41), .CO (n_45), .S (n_46));
  DFFRHQX8 \s_pc_reg[11] (.RN (i_rstn), .CK (i_clk), .D (n_43), .Q
       (o_pc[11]));
  AOI22X1 g2457__1474(.A0 (n_114), .A1 (n_42), .B0 (i_stall), .B1
       (o_pc[12]), .Y (n_44));
  OAI2BB1X1 g2460__4547(.A0N (i_target[11]), .A1N (n_116), .B0 (n_40),
       .Y (n_43));
  ADDHX1 g2459__9682(.A (o_pc[12]), .B (n_37), .CO (n_41), .S (n_42));
  DFFRHQX8 \s_pc_reg[10] (.RN (i_rstn), .CK (i_clk), .D (n_39), .Q
       (o_pc[10]));
  AOI22X1 g2461__2683(.A0 (n_114), .A1 (n_38), .B0 (i_stall), .B1
       (o_pc[11]), .Y (n_40));
  OAI2BB1X1 g2464__1309(.A0N (i_target[10]), .A1N (n_116), .B0 (n_36),
       .Y (n_39));
  ADDHX1 g2463__6877(.A (o_pc[11]), .B (n_33), .CO (n_37), .S (n_38));
  AOI22X1 g2465__2900(.A0 (n_114), .A1 (n_34), .B0 (i_stall), .B1
       (o_pc[10]), .Y (n_36));
  DFFRHQX8 \s_pc_reg[9] (.RN (i_rstn), .CK (i_clk), .D (n_35), .Q
       (o_pc[9]));
  OAI2BB1X1 g2468__2391(.A0N (i_target[9]), .A1N (n_116), .B0 (n_32),
       .Y (n_35));
  ADDHX1 g2467__7675(.A (o_pc[10]), .B (n_29), .CO (n_33), .S (n_34));
  DFFRHQX8 \s_pc_reg[8] (.RN (i_rstn), .CK (i_clk), .D (n_31), .Q
       (o_pc[8]));
  AOI22X1 g2469__7118(.A0 (n_114), .A1 (n_30), .B0 (i_stall), .B1
       (o_pc[9]), .Y (n_32));
  OAI2BB1X1 g2472__8757(.A0N (i_target[8]), .A1N (n_116), .B0 (n_28),
       .Y (n_31));
  ADDHX1 g2471__1786(.A (o_pc[9]), .B (n_25), .CO (n_29), .S (n_30));
  DFFRHQX8 \s_pc_reg[7] (.RN (i_rstn), .CK (i_clk), .D (n_27), .Q
       (o_pc[7]));
  AOI22X1 g2473__5953(.A0 (n_114), .A1 (n_26), .B0 (i_stall), .B1
       (o_pc[8]), .Y (n_28));
  OAI2BB1X1 g2476__5703(.A0N (i_target[7]), .A1N (n_116), .B0 (n_24),
       .Y (n_27));
  ADDHX1 g2475__7114(.A (o_pc[8]), .B (n_21), .CO (n_25), .S (n_26));
  DFFRHQX8 \s_pc_reg[6] (.RN (i_rstn), .CK (i_clk), .D (n_23), .Q
       (o_pc[6]));
  AOI22X1 g2477__5266(.A0 (n_114), .A1 (n_22), .B0 (i_stall), .B1
       (o_pc[7]), .Y (n_24));
  OAI2BB1X1 g2480__2250(.A0N (i_target[6]), .A1N (n_116), .B0 (n_20),
       .Y (n_23));
  ADDHX1 g2479__6083(.A (o_pc[7]), .B (n_17), .CO (n_21), .S (n_22));
  AOI22X1 g2481__2703(.A0 (n_114), .A1 (n_18), .B0 (i_stall), .B1
       (o_pc[6]), .Y (n_20));
  DFFRHQX8 \s_pc_reg[5] (.RN (i_rstn), .CK (i_clk), .D (n_19), .Q
       (o_pc[5]));
  OAI2BB1X1 g2484__5795(.A0N (i_target[5]), .A1N (n_116), .B0 (n_16),
       .Y (n_19));
  ADDHX1 g2483__7344(.A (o_pc[6]), .B (n_13), .CO (n_17), .S (n_18));
  AOI22X1 g2485__1840(.A0 (n_114), .A1 (n_14), .B0 (i_stall), .B1
       (o_pc[5]), .Y (n_16));
  DFFRHQX8 \s_pc_reg[4] (.RN (i_rstn), .CK (i_clk), .D (n_15), .Q
       (o_pc[4]));
  OAI2BB1X1 g2488__5019(.A0N (i_target[4]), .A1N (n_116), .B0 (n_12),
       .Y (n_15));
  ADDHX1 g2487__1857(.A (o_pc[5]), .B (n_9), .CO (n_13), .S (n_14));
  AOI22X1 g2489__9906(.A0 (n_114), .A1 (n_10), .B0 (i_stall), .B1
       (o_pc[4]), .Y (n_12));
  DFFRHQX8 \s_pc_reg[3] (.RN (i_rstn), .CK (i_clk), .D (n_11), .Q
       (o_pc[3]));
  OAI2BB1X1 g2492__8780(.A0N (i_target[3]), .A1N (n_116), .B0 (n_8), .Y
       (n_11));
  DFFRHQX8 \s_pc_reg[2] (.RN (i_rstn), .CK (i_clk), .D (n_7), .Q
       (o_pc[2]));
  ADDHX1 g2491__4296(.A (o_pc[4]), .B (n_2), .CO (n_9), .S (n_10));
  AOI22X1 g2494__3772(.A0 (n_114), .A1 (n_3), .B0 (i_stall), .B1
       (o_pc[3]), .Y (n_8));
  OAI221X1 g2496__1474(.A0 (n_6), .A1 (n_0), .B0 (n_5), .B1 (o_pc[2]),
       .C0 (n_4), .Y (n_7));
  SDFFRHQX8 \s_pc_reg[0] (.RN (i_rstn), .CK (i_clk), .D (o_pc[0]), .SI
       (i_target[0]), .SE (n_116), .Q (o_pc[0]));
  SDFFRHQX8 \s_pc_reg[1] (.RN (i_rstn), .CK (i_clk), .D (o_pc[1]), .SI
       (i_target[1]), .SE (n_116), .Q (o_pc[1]));
  NAND2X1 g2499__4547(.A (i_target[2]), .B (n_116), .Y (n_4));
  ADDHX1 g2498__9682(.A (o_pc[3]), .B (o_pc[2]), .CO (n_2), .S (n_3));
  AND2X1 g2500__2683(.A (n_6), .B (i_transfert), .Y (n_116));
  INVX1 g2501(.A (n_114), .Y (n_5));
  NOR2X2 g2502__1309(.A (i_transfert), .B (i_stall), .Y (n_114));
  INVX1 g2503(.A (o_pc[30]), .Y (n_1));
  INVX1 g2504(.A (o_pc[2]), .Y (n_0));
  INVX1 g2505(.A (i_stall), .Y (n_6));
endmodule

