
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Dec  9 2021 01:38:06 EST (Dec  9 2021 06:38:06 UTC)

// Verification Directory fv/riscv_pc 

module riscv_pc(i_clk, i_rstn, i_stall, i_transfert, i_target, o_pc);
  input i_clk, i_rstn, i_stall, i_transfert;
  input [31:0] i_target;
  output [31:0] o_pc;
  wire i_clk, i_rstn, i_stall, i_transfert;
  wire [31:0] i_target;
  wire [31:0] o_pc;
  wire [31:0] \X_ADDER_s_carry[1] ;
  wire n_70, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189;
  wire n_190, n_191, n_192, n_193, n_194, n_195, n_196, n_197;
  wire n_198, n_200, n_201, n_410, n_412, n_413, n_414, n_415;
  wire n_416, n_417, n_418, n_419, n_420, n_421, n_422, n_423;
  wire n_424, n_425, n_426, n_427, n_428, n_429, n_430, n_431;
  wire n_432, n_435, n_436, n_437, n_438, n_439, n_440, n_441;
  wire n_450, n_451, n_452, n_453, n_462, n_463, n_464, n_465;
  wire n_470, n_471, n_476, n_477, n_486, n_487, n_488, n_489;
  wire n_498, n_499, n_500, n_501, n_510, n_511, n_512, n_513;
  wire n_522, n_523, n_524, n_525, n_534, n_535, n_536, n_537;
  wire n_546, n_547, n_548, n_549, n_558, n_559, n_560, n_561;
  wire n_570, n_571, n_572, n_573, n_582, n_583, n_584, n_585;
  wire n_594, n_595, n_596, n_597, n_606, n_607, n_608, n_609;
  wire n_618, n_619, n_620, n_621, n_630, n_631, n_632, n_633;
  wire n_642, n_643, n_644, n_645, n_654, n_655, n_656, n_657;
  wire n_666, n_667, n_668, n_669, n_678, n_679, n_680, n_681;
  wire n_690, n_691, n_692, n_693, n_702, n_703, n_704, n_705;
  wire n_714, n_715, n_716, n_717, n_726, n_727, n_728, n_729;
  wire n_738, n_739, n_740, n_741, n_750, n_751, n_752, n_753;
  wire n_762, n_763, n_764, n_765, n_774, n_775, n_776, n_777;
  wire n_784, n_785, n_786, n_795, n_796, n_797, n_798, n_801;
  wire n_812, n_813, n_814, n_815, n_816, n_825, n_826, n_827;
  wire n_828, n_833, n_834, n_835, n_836, n_837, n_838, n_839;
  wire n_840, n_841, n_842, n_843, n_844, n_845, n_846, n_847;
  wire n_848, n_849, n_850, n_851, n_852, n_853, n_854, n_855;
  wire n_856, n_857, n_858, n_859, n_860, n_861, n_862, n_863;
  wire n_864, n_865, n_866, n_867, n_868, n_869, n_870, n_871;
  wire n_872, n_873, n_874, n_875, n_876, n_877, n_878, n_879;
  wire n_880, n_881, n_882, n_883, n_884, n_885, n_886;
  not g39 (n_70, i_rstn);
  or g602 (n_198, wc, n_828);
  not gc (wc, n_827);
  nand g603 (n_828, n_825, n_826);
  or g604 (n_197, wc0, n_816);
  not gc0 (wc0, n_815);
  or g605 (n_825, wc1, n_200);
  not gc1 (wc1, n_412);
  nand g606 (n_815, o_pc[30], n_410);
  or g607 (n_196, wc2, n_798);
  not gc2 (wc2, n_797);
  nand g608 (n_412, n_785, n_786);
  nand g609 (n_816, n_813, n_814);
  nand g610 (n_826, o_pc[31], n_410);
  or g611 (n_410, wc3, i_stall);
  not gc3 (wc3, n_801);
  nand g612 (n_798, n_795, n_796);
  or g613 (n_785, n_784, o_pc[31]);
  or g614 (n_195, wc4, n_777);
  not gc4 (wc4, n_776);
  or g615 (n_813, n_812, n_200);
  or g616 (n_812, \X_ADDER_s_carry[1] [29], o_pc[30]);
  nand g617 (n_777, n_774, n_775);
  or g618 (n_801, wc5, n_200);
  not gc5 (wc5, \X_ADDER_s_carry[1] [29]);
  or g619 (n_795, wc6, n_200);
  not gc6 (wc6, n_413);
  or g620 (n_194, wc7, n_765);
  not gc7 (wc7, n_764);
  or g621 (n_784, \X_ADDER_s_carry[1] [29], wc8);
  not gc8 (wc8, o_pc[30]);
  or g622 (n_833, \X_ADDER_s_carry[1] [28], o_pc[29]);
  nand g623 (n_834, \X_ADDER_s_carry[1] [28], o_pc[29]);
  nand g624 (n_413, n_833, n_834);
  or g625 (\X_ADDER_s_carry[1] [29], \X_ADDER_s_carry[1] [28], wc9);
  not gc9 (wc9, o_pc[29]);
  or g626 (n_774, wc10, n_200);
  not gc10 (wc10, n_414);
  or g627 (n_193, wc11, n_753);
  not gc11 (wc11, n_752);
  nand g628 (n_765, n_762, n_763);
  or g629 (n_835, \X_ADDER_s_carry[1] [27], o_pc[28]);
  nand g630 (n_836, \X_ADDER_s_carry[1] [27], o_pc[28]);
  nand g631 (n_414, n_835, n_836);
  or g632 (n_762, wc12, n_200);
  not gc12 (wc12, n_415);
  nand g633 (n_753, n_750, n_751);
  or g634 (n_192, wc13, n_741);
  not gc13 (wc13, n_740);
  or g635 (\X_ADDER_s_carry[1] [28], \X_ADDER_s_carry[1] [27], wc14);
  not gc14 (wc14, o_pc[28]);
  or g636 (n_191, wc15, n_729);
  not gc15 (wc15, n_728);
  or g637 (n_837, \X_ADDER_s_carry[1] [26], o_pc[27]);
  nand g638 (n_838, \X_ADDER_s_carry[1] [26], o_pc[27]);
  nand g639 (n_415, n_837, n_838);
  nand g640 (n_741, n_738, n_739);
  or g641 (\X_ADDER_s_carry[1] [27], \X_ADDER_s_carry[1] [26], wc16);
  not gc16 (wc16, o_pc[27]);
  or g642 (n_750, wc17, n_200);
  not gc17 (wc17, n_416);
  or g643 (n_190, wc18, n_717);
  not gc18 (wc18, n_716);
  or g644 (\X_ADDER_s_carry[1] [26], \X_ADDER_s_carry[1] [25], wc19);
  not gc19 (wc19, o_pc[26]);
  or g645 (n_738, wc20, n_200);
  not gc20 (wc20, n_417);
  or g646 (n_839, \X_ADDER_s_carry[1] [25], o_pc[26]);
  nand g647 (n_840, \X_ADDER_s_carry[1] [25], o_pc[26]);
  nand g648 (n_416, n_839, n_840);
  nand g649 (n_729, n_726, n_727);
  or g650 (n_726, wc21, n_200);
  not gc21 (wc21, n_418);
  or g651 (n_189, wc22, n_705);
  not gc22 (wc22, n_704);
  or g652 (n_841, \X_ADDER_s_carry[1] [24], o_pc[25]);
  nand g653 (n_842, \X_ADDER_s_carry[1] [24], o_pc[25]);
  nand g654 (n_417, n_841, n_842);
  or g655 (\X_ADDER_s_carry[1] [25], \X_ADDER_s_carry[1] [24], wc23);
  not gc23 (wc23, o_pc[25]);
  nand g656 (n_717, n_714, n_715);
  or g657 (n_714, wc24, n_200);
  not gc24 (wc24, n_419);
  nand g658 (n_705, n_702, n_703);
  or g659 (n_188, wc25, n_693);
  not gc25 (wc25, n_692);
  or g660 (n_843, \X_ADDER_s_carry[1] [23], o_pc[24]);
  nand g661 (n_844, \X_ADDER_s_carry[1] [23], o_pc[24]);
  nand g662 (n_418, n_843, n_844);
  or g663 (\X_ADDER_s_carry[1] [24], \X_ADDER_s_carry[1] [23], wc26);
  not gc26 (wc26, o_pc[24]);
  nand g664 (n_693, n_690, n_691);
  or g665 (n_845, \X_ADDER_s_carry[1] [22], o_pc[23]);
  nand g666 (n_846, \X_ADDER_s_carry[1] [22], o_pc[23]);
  nand g667 (n_419, n_845, n_846);
  or g668 (n_702, wc27, n_200);
  not gc27 (wc27, n_420);
  or g669 (\X_ADDER_s_carry[1] [23], \X_ADDER_s_carry[1] [22], wc28);
  not gc28 (wc28, o_pc[23]);
  or g670 (n_187, wc29, n_681);
  not gc29 (wc29, n_680);
  nand g671 (n_681, n_678, n_679);
  or g672 (n_690, wc30, n_200);
  not gc30 (wc30, n_421);
  or g673 (\X_ADDER_s_carry[1] [22], \X_ADDER_s_carry[1] [21], wc31);
  not gc31 (wc31, o_pc[22]);
  or g674 (n_847, \X_ADDER_s_carry[1] [21], o_pc[22]);
  nand g675 (n_848, \X_ADDER_s_carry[1] [21], o_pc[22]);
  nand g676 (n_420, n_847, n_848);
  or g677 (n_186, wc32, n_669);
  not gc32 (wc32, n_668);
  or g678 (n_185, wc33, n_657);
  not gc33 (wc33, n_656);
  or g679 (n_849, \X_ADDER_s_carry[1] [20], o_pc[21]);
  nand g680 (n_850, \X_ADDER_s_carry[1] [20], o_pc[21]);
  nand g681 (n_421, n_849, n_850);
  or g682 (n_678, wc34, n_200);
  not gc34 (wc34, n_422);
  or g683 (\X_ADDER_s_carry[1] [21], \X_ADDER_s_carry[1] [20], wc35);
  not gc35 (wc35, o_pc[21]);
  nand g684 (n_669, n_666, n_667);
  or g685 (n_851, \X_ADDER_s_carry[1] [19], o_pc[20]);
  nand g686 (n_852, \X_ADDER_s_carry[1] [19], o_pc[20]);
  nand g687 (n_422, n_851, n_852);
  or g688 (\X_ADDER_s_carry[1] [20], \X_ADDER_s_carry[1] [19], wc36);
  not gc36 (wc36, o_pc[20]);
  or g689 (n_184, wc37, n_645);
  not gc37 (wc37, n_644);
  nand g690 (n_657, n_654, n_655);
  or g691 (n_666, wc38, n_200);
  not gc38 (wc38, n_423);
  or g692 (n_654, wc39, n_200);
  not gc39 (wc39, n_424);
  or g693 (n_183, wc40, n_633);
  not gc40 (wc40, n_632);
  or g694 (n_853, \X_ADDER_s_carry[1] [18], o_pc[19]);
  nand g695 (n_854, \X_ADDER_s_carry[1] [18], o_pc[19]);
  nand g696 (n_423, n_853, n_854);
  or g697 (\X_ADDER_s_carry[1] [19], \X_ADDER_s_carry[1] [18], wc41);
  not gc41 (wc41, o_pc[19]);
  nand g698 (n_645, n_642, n_643);
  or g699 (n_855, \X_ADDER_s_carry[1] [17], o_pc[18]);
  nand g700 (n_856, \X_ADDER_s_carry[1] [17], o_pc[18]);
  nand g701 (n_424, n_855, n_856);
  or g702 (n_642, wc42, n_200);
  not gc42 (wc42, n_425);
  nand g703 (n_633, n_630, n_631);
  or g704 (n_182, wc43, n_621);
  not gc43 (wc43, n_620);
  or g705 (\X_ADDER_s_carry[1] [18], \X_ADDER_s_carry[1] [17], wc44);
  not gc44 (wc44, o_pc[18]);
  nand g706 (n_621, n_618, n_619);
  or g707 (n_857, \X_ADDER_s_carry[1] [16], o_pc[17]);
  nand g708 (n_858, \X_ADDER_s_carry[1] [16], o_pc[17]);
  nand g709 (n_425, n_857, n_858);
  or g710 (\X_ADDER_s_carry[1] [17], \X_ADDER_s_carry[1] [16], wc45);
  not gc45 (wc45, o_pc[17]);
  or g711 (n_630, wc46, n_200);
  not gc46 (wc46, n_426);
  or g712 (n_181, wc47, n_609);
  not gc47 (wc47, n_608);
  nand g713 (n_609, n_606, n_607);
  or g714 (n_180, wc48, n_597);
  not gc48 (wc48, n_596);
  or g715 (n_859, \X_ADDER_s_carry[1] [15], o_pc[16]);
  nand g716 (n_860, \X_ADDER_s_carry[1] [15], o_pc[16]);
  nand g717 (n_426, n_859, n_860);
  or g718 (\X_ADDER_s_carry[1] [16], \X_ADDER_s_carry[1] [15], wc49);
  not gc49 (wc49, o_pc[16]);
  or g719 (n_618, wc50, n_200);
  not gc50 (wc50, n_427);
  or g720 (n_179, wc51, n_585);
  not gc51 (wc51, n_584);
  nand g721 (n_597, n_594, n_595);
  or g722 (n_861, \X_ADDER_s_carry[1] [14], o_pc[15]);
  nand g723 (n_862, \X_ADDER_s_carry[1] [14], o_pc[15]);
  nand g724 (n_427, n_861, n_862);
  or g725 (\X_ADDER_s_carry[1] [15], \X_ADDER_s_carry[1] [14], wc52);
  not gc52 (wc52, o_pc[15]);
  or g726 (n_606, wc53, n_200);
  not gc53 (wc53, n_428);
  or g727 (n_863, \X_ADDER_s_carry[1] [13], o_pc[14]);
  nand g728 (n_864, \X_ADDER_s_carry[1] [13], o_pc[14]);
  nand g729 (n_428, n_863, n_864);
  or g730 (\X_ADDER_s_carry[1] [14], \X_ADDER_s_carry[1] [13], wc54);
  not gc54 (wc54, o_pc[14]);
  or g731 (n_594, wc55, n_200);
  not gc55 (wc55, n_429);
  nand g732 (n_585, n_582, n_583);
  or g733 (n_178, wc56, n_573);
  not gc56 (wc56, n_572);
  or g734 (n_582, wc57, n_200);
  not gc57 (wc57, n_430);
  nand g735 (n_573, n_570, n_571);
  or g736 (n_865, \X_ADDER_s_carry[1] [12], o_pc[13]);
  nand g737 (n_866, \X_ADDER_s_carry[1] [12], o_pc[13]);
  nand g738 (n_429, n_865, n_866);
  or g739 (n_177, wc58, n_561);
  not gc58 (wc58, n_560);
  or g740 (\X_ADDER_s_carry[1] [13], \X_ADDER_s_carry[1] [12], wc59);
  not gc59 (wc59, o_pc[13]);
  or g741 (\X_ADDER_s_carry[1] [12], \X_ADDER_s_carry[1] [11], wc60);
  not gc60 (wc60, o_pc[12]);
  or g742 (n_570, wc61, n_200);
  not gc61 (wc61, n_431);
  or g743 (n_176, wc62, n_549);
  not gc62 (wc62, n_548);
  or g744 (n_867, \X_ADDER_s_carry[1] [11], o_pc[12]);
  nand g745 (n_868, \X_ADDER_s_carry[1] [11], o_pc[12]);
  nand g746 (n_430, n_867, n_868);
  nand g747 (n_561, n_558, n_559);
  or g748 (n_175, wc63, n_537);
  not gc63 (wc63, n_536);
  or g749 (n_869, \X_ADDER_s_carry[1] [10], o_pc[11]);
  nand g750 (n_870, \X_ADDER_s_carry[1] [10], o_pc[11]);
  nand g751 (n_431, n_869, n_870);
  or g752 (n_558, wc64, n_200);
  not gc64 (wc64, n_432);
  nand g753 (n_549, n_546, n_547);
  or g754 (\X_ADDER_s_carry[1] [11], \X_ADDER_s_carry[1] [10], wc65);
  not gc65 (wc65, o_pc[11]);
  or g755 (n_871, \X_ADDER_s_carry[1] [9], o_pc[10]);
  nand g756 (n_872, \X_ADDER_s_carry[1] [9], o_pc[10]);
  nand g757 (n_432, n_871, n_872);
  or g758 (n_174, wc66, n_525);
  not gc66 (wc66, n_524);
  or g759 (n_546, wc67, n_200);
  not gc67 (wc67, n_435);
  nand g760 (n_537, n_534, n_535);
  or g761 (\X_ADDER_s_carry[1] [10], \X_ADDER_s_carry[1] [9], wc68);
  not gc68 (wc68, o_pc[10]);
  or g762 (n_173, wc69, n_513);
  not gc69 (wc69, n_512);
  or g763 (n_873, \X_ADDER_s_carry[1] [8], o_pc[9]);
  nand g764 (n_874, \X_ADDER_s_carry[1] [8], o_pc[9]);
  nand g765 (n_435, n_873, n_874);
  or g766 (n_534, wc70, n_200);
  not gc70 (wc70, n_438);
  or g767 (\X_ADDER_s_carry[1] [9], \X_ADDER_s_carry[1] [8], wc71);
  not gc71 (wc71, o_pc[9]);
  nand g768 (n_525, n_522, n_523);
  or g769 (n_875, \X_ADDER_s_carry[1] [7], o_pc[8]);
  nand g770 (n_876, \X_ADDER_s_carry[1] [7], o_pc[8]);
  nand g771 (n_438, n_875, n_876);
  or g772 (n_172, wc72, n_501);
  not gc72 (wc72, n_500);
  or g773 (n_522, wc73, n_200);
  not gc73 (wc73, n_437);
  or g774 (\X_ADDER_s_carry[1] [8], \X_ADDER_s_carry[1] [7], wc74);
  not gc74 (wc74, o_pc[8]);
  nand g775 (n_513, n_510, n_511);
  nand g776 (n_501, n_498, n_499);
  or g777 (\X_ADDER_s_carry[1] [7], \X_ADDER_s_carry[1] [6], wc75);
  not gc75 (wc75, o_pc[7]);
  or g778 (n_877, \X_ADDER_s_carry[1] [6], o_pc[7]);
  nand g779 (n_878, \X_ADDER_s_carry[1] [6], o_pc[7]);
  nand g780 (n_437, n_877, n_878);
  or g781 (n_510, wc76, n_200);
  not gc76 (wc76, n_440);
  or g782 (n_171, wc77, n_489);
  not gc77 (wc77, n_488);
  or g783 (n_169, wc78, n_453);
  not gc78 (wc78, n_452);
  or g784 (n_498, wc79, n_200);
  not gc79 (wc79, n_441);
  or g785 (n_879, \X_ADDER_s_carry[1] [5], o_pc[6]);
  nand g786 (n_880, \X_ADDER_s_carry[1] [5], o_pc[6]);
  nand g787 (n_440, n_879, n_880);
  or g788 (n_170, wc80, n_465);
  not gc80 (wc80, n_464);
  or g789 (\X_ADDER_s_carry[1] [6], \X_ADDER_s_carry[1] [5], wc81);
  not gc81 (wc81, o_pc[6]);
  nand g790 (n_489, n_486, n_487);
  nand g791 (n_168, n_476, n_477);
  nand g792 (n_167, n_470, n_471);
  or g793 (n_486, wc82, n_200);
  not gc82 (wc82, n_436);
  nand g794 (n_465, n_462, n_463);
  nand g795 (n_453, n_450, n_451);
  or g796 (n_881, \X_ADDER_s_carry[1] [4], o_pc[5]);
  nand g797 (n_882, \X_ADDER_s_carry[1] [4], o_pc[5]);
  nand g798 (n_441, n_881, n_882);
  or g799 (\X_ADDER_s_carry[1] [5], \X_ADDER_s_carry[1] [4], wc83);
  not gc83 (wc83, o_pc[5]);
  or g800 (n_752, n_201, wc84);
  not gc84 (wc84, i_target[26]);
  or g801 (n_488, n_201, wc85);
  not gc85 (wc85, i_target[4]);
  or g802 (n_500, n_201, wc86);
  not gc86 (wc86, i_target[5]);
  nand g803 (n_476, n_201, o_pc[1]);
  or g804 (n_477, n_201, wc87);
  not gc87 (wc87, i_target[1]);
  or g805 (n_740, n_201, wc88);
  not gc88 (wc88, i_target[25]);
  nand g806 (n_470, n_201, o_pc[0]);
  or g807 (n_471, n_201, wc89);
  not gc89 (wc89, i_target[0]);
  or g808 (\X_ADDER_s_carry[1] [4], \X_ADDER_s_carry[1] [3], wc90);
  not gc90 (wc90, o_pc[4]);
  or g809 (n_524, n_201, wc91);
  not gc91 (wc91, i_target[7]);
  or g810 (n_464, n_201, wc92);
  not gc92 (wc92, i_target[3]);
  or g811 (n_728, n_201, wc93);
  not gc93 (wc93, i_target[24]);
  or g812 (n_462, wc94, n_200);
  not gc94 (wc94, n_439);
  or g813 (n_536, n_201, wc95);
  not gc95 (wc95, i_target[8]);
  or g814 (n_548, n_201, wc96);
  not gc96 (wc96, i_target[9]);
  or g815 (n_764, n_201, wc97);
  not gc97 (wc97, i_target[27]);
  or g816 (n_451, n_201, wc98);
  not gc98 (wc98, i_target[2]);
  or g817 (n_450, n_200, o_pc[2]);
  or g818 (n_716, n_201, wc99);
  not gc99 (wc99, i_target[23]);
  or g819 (n_560, n_201, wc100);
  not gc100 (wc100, i_target[10]);
  or g820 (n_572, n_201, wc101);
  not gc101 (wc101, i_target[11]);
  or g821 (n_704, n_201, wc102);
  not gc102 (wc102, i_target[22]);
  or g822 (n_584, n_201, wc103);
  not gc103 (wc103, i_target[12]);
  or g823 (n_883, \X_ADDER_s_carry[1] [3], o_pc[4]);
  nand g824 (n_884, \X_ADDER_s_carry[1] [3], o_pc[4]);
  nand g825 (n_436, n_883, n_884);
  or g826 (n_596, n_201, wc104);
  not gc104 (wc104, i_target[13]);
  or g827 (n_692, n_201, wc105);
  not gc105 (wc105, i_target[21]);
  or g828 (n_608, n_201, wc106);
  not gc106 (wc106, i_target[14]);
  or g829 (n_680, n_201, wc107);
  not gc107 (wc107, i_target[20]);
  or g830 (n_620, n_201, wc108);
  not gc108 (wc108, i_target[15]);
  or g831 (n_668, n_201, wc109);
  not gc109 (wc109, i_target[19]);
  or g832 (n_656, n_201, wc110);
  not gc110 (wc110, i_target[18]);
  or g833 (n_776, n_201, wc111);
  not gc111 (wc111, i_target[28]);
  or g834 (n_644, n_201, wc112);
  not gc112 (wc112, i_target[17]);
  or g835 (n_632, n_201, wc113);
  not gc113 (wc113, i_target[16]);
  or g836 (n_797, n_201, wc114);
  not gc114 (wc114, i_target[29]);
  or g837 (n_814, n_201, wc115);
  not gc115 (wc115, i_target[30]);
  or g838 (n_827, n_201, wc116);
  not gc116 (wc116, i_target[31]);
  or g839 (n_512, n_201, wc117);
  not gc117 (wc117, i_target[6]);
  or g840 (n_885, wc118, o_pc[3]);
  not gc118 (wc118, o_pc[2]);
  or g841 (n_886, o_pc[2], wc119);
  not gc119 (wc119, o_pc[3]);
  nand g842 (n_439, n_885, n_886);
  nand g843 (n_452, o_pc[2], i_stall);
  nand g844 (n_463, o_pc[3], i_stall);
  nand g845 (n_487, o_pc[4], i_stall);
  or g846 (n_201, i_stall, wc120);
  not gc120 (wc120, i_transfert);
  or g847 (n_200, i_stall, i_transfert);
  nand g848 (n_499, o_pc[5], i_stall);
  nand g849 (n_511, o_pc[6], i_stall);
  nand g850 (n_523, o_pc[7], i_stall);
  nand g851 (n_535, o_pc[8], i_stall);
  nand g852 (n_547, o_pc[9], i_stall);
  nand g853 (n_559, o_pc[10], i_stall);
  nand g854 (n_571, o_pc[11], i_stall);
  nand g855 (n_583, o_pc[12], i_stall);
  nand g856 (n_595, o_pc[13], i_stall);
  nand g857 (n_607, o_pc[14], i_stall);
  nand g858 (n_619, o_pc[15], i_stall);
  nand g859 (n_631, o_pc[16], i_stall);
  nand g860 (n_643, o_pc[17], i_stall);
  nand g861 (n_655, o_pc[18], i_stall);
  nand g862 (n_667, o_pc[19], i_stall);
  nand g863 (n_679, o_pc[20], i_stall);
  nand g864 (n_691, o_pc[21], i_stall);
  nand g865 (n_703, o_pc[22], i_stall);
  nand g866 (n_715, o_pc[23], i_stall);
  nand g867 (n_727, o_pc[24], i_stall);
  nand g868 (n_739, o_pc[25], i_stall);
  nand g869 (n_751, o_pc[26], i_stall);
  nand g870 (n_763, o_pc[27], i_stall);
  nand g871 (n_775, o_pc[28], i_stall);
  or g872 (n_786, o_pc[30], wc121);
  not gc121 (wc121, o_pc[31]);
  nand g873 (n_796, o_pc[29], i_stall);
  nand g874 (\X_ADDER_s_carry[1] [3], o_pc[2], o_pc[3]);
  CDN_flop \s_pc_reg[0] (.clk (i_clk), .d (n_167), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[0]));
  CDN_flop \s_pc_reg[1] (.clk (i_clk), .d (n_168), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[1]));
  CDN_flop \s_pc_reg[2] (.clk (i_clk), .d (n_169), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[2]));
  CDN_flop \s_pc_reg[3] (.clk (i_clk), .d (n_170), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[3]));
  CDN_flop \s_pc_reg[4] (.clk (i_clk), .d (n_171), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[4]));
  CDN_flop \s_pc_reg[5] (.clk (i_clk), .d (n_172), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[5]));
  CDN_flop \s_pc_reg[6] (.clk (i_clk), .d (n_173), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[6]));
  CDN_flop \s_pc_reg[7] (.clk (i_clk), .d (n_174), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[7]));
  CDN_flop \s_pc_reg[8] (.clk (i_clk), .d (n_175), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[8]));
  CDN_flop \s_pc_reg[9] (.clk (i_clk), .d (n_176), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[9]));
  CDN_flop \s_pc_reg[10] (.clk (i_clk), .d (n_177), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[10]));
  CDN_flop \s_pc_reg[11] (.clk (i_clk), .d (n_178), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[11]));
  CDN_flop \s_pc_reg[12] (.clk (i_clk), .d (n_179), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[12]));
  CDN_flop \s_pc_reg[13] (.clk (i_clk), .d (n_180), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[13]));
  CDN_flop \s_pc_reg[14] (.clk (i_clk), .d (n_181), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[14]));
  CDN_flop \s_pc_reg[15] (.clk (i_clk), .d (n_182), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[15]));
  CDN_flop \s_pc_reg[16] (.clk (i_clk), .d (n_183), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[16]));
  CDN_flop \s_pc_reg[17] (.clk (i_clk), .d (n_184), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[17]));
  CDN_flop \s_pc_reg[18] (.clk (i_clk), .d (n_185), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[18]));
  CDN_flop \s_pc_reg[19] (.clk (i_clk), .d (n_186), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[19]));
  CDN_flop \s_pc_reg[20] (.clk (i_clk), .d (n_187), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[20]));
  CDN_flop \s_pc_reg[21] (.clk (i_clk), .d (n_188), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[21]));
  CDN_flop \s_pc_reg[22] (.clk (i_clk), .d (n_189), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[22]));
  CDN_flop \s_pc_reg[23] (.clk (i_clk), .d (n_190), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[23]));
  CDN_flop \s_pc_reg[24] (.clk (i_clk), .d (n_191), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[24]));
  CDN_flop \s_pc_reg[25] (.clk (i_clk), .d (n_192), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[25]));
  CDN_flop \s_pc_reg[26] (.clk (i_clk), .d (n_193), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[26]));
  CDN_flop \s_pc_reg[27] (.clk (i_clk), .d (n_194), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[27]));
  CDN_flop \s_pc_reg[28] (.clk (i_clk), .d (n_195), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[28]));
  CDN_flop \s_pc_reg[29] (.clk (i_clk), .d (n_196), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[29]));
  CDN_flop \s_pc_reg[30] (.clk (i_clk), .d (n_197), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[30]));
  CDN_flop \s_pc_reg[31] (.clk (i_clk), .d (n_198), .sena (1'b1), .aclr
       (n_70), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (o_pc[31]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
